# Generated by Django 4.0.1 on 2022-01-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_alter_entreprise_sigle_alter_entreprise_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='village',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projet.village'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='debut',
            field=models.DateField(verbose_name='Date début'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='doc_projet',
            field=models.FileField(upload_to='', verbose_name='Document projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='execut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.annee_exec', verbose_name="Année d'exécution"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='fin',
            field=models.DateField(verbose_name='Date fin'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='montant_alloue',
            field=models.IntegerField(verbose_name='Montant alloué'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet.partenaire', verbose_name='Financé par'),
        ),
    ]
