# Generated by Django 4.0.1 on 2022-01-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0004_projet_village_alter_projet_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projet.departement'),
        ),
    ]
