# Generated by Django 4.0.1 on 2022-01-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0005_village_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='departement',
        ),
    ]
